insert into Clientes (Nome, Cidade, UF) values
('Ana Clara Silva', 'São Paulo', 'SP'),
('Pedro Henrique Costa', 'Rio de Janeiro', 'RJ'),
('Maria Eduarda Santos', 'Salvador', 'BA'),
('João Victor Almeida', 'Fortaleza', 'CE'),
('Laura Beatriz Oliveira', 'Belo Horizonte', 'MG'),
('Lucas Guilherme Ferreira', 'Curitiba', 'PR'),
('Sofia Isabel Souza', 'Manaus', 'AM'),
('Gabriel Rafael Rodrigues', 'Recife', 'PE'),
('Alice Fernanda Pereira', 'Porto Alegre', 'RS'),
('Matheus Antônio Martins', 'Brasília', 'DF'),
('Anya Celeste Gomes', 'Belém', 'PA'),
('Kai Ethan Carvalho', 'Goiânia', 'GO'),
('Nova Isabella Nunes', 'Vitória', 'ES'),
('Jax Gabriel Lima', 'Campo Grande', 'MS'),
('Indie Sophia Moraes', 'Macapá', 'AP'),
('Atlas Benjamin Ribeiro', 'Boa Vista', 'RR'),
('Sky Camila Barros', 'Palmas', 'TO'),
('River Larissa Vicente', 'Maceió', 'AL'),
('Nexus Amanda Santos', 'João Pessoa', 'PB'),
('Zayn Miguel Costa', 'Natal', 'RN'),
('Aeron Stark', 'Florianópolis', 'SC'),
('Nyx Malfoy', 'Aracaju', 'SE'),
('Oberon Targaryen', 'Teresina', 'PI'),
('Elara Snow', 'São Luís', 'MA'),
('Kael Greyjoy', 'Macapá', 'AP'),
('Lyra Lannister', 'Boa Vista', 'RR'),
('Orion Martell', 'Palmas', 'TO'),
('Seraphina Baratheon', 'Maceió', 'AL'),
('Silas Tyrell', 'João Pessoa', 'PB'),
('Thalia Boltons', 'Natal', 'RN'),
('Sol Silva', 'Florianópolis', 'SC'),
('Lua Oliveira', 'Aracaju', 'SE'),
('Mar Santos', 'Teresina', 'PI'),
('Céu Campos', 'São Luís', 'MA'),
('Água Ferreira', 'Macapá', 'AP'),
('Terra Teixeira', 'Boa Vista', 'RR'),
('Floresta Almeida', 'Palmas', 'TO'),
('Aurora Soares', 'Maceió', 'AL'),
('Nívea Gomes', 'João Pessoa', 'PB'),
('Zephyr Carvalho', 'Natal', 'RN'),
('Akira Tanaka', 'São Paulo', 'SP'),
('Leila Al-Rashid', 'Rio de Janeiro', 'RJ'),
('Nikos Papadopoulos', 'Salvador', 'BA'),
('Anya Petrova', 'Fortaleza', 'CE'),
('Kai Lee', 'Belo Horizonte', 'MG'),
('Zara Hernandez', 'Curitiba', 'PR'),
('Noah Cohen', 'Manaus', 'AM'),
('Marcos Roberto', 'Recife', 'PE'),
('Luca Rossi', 'Porto Alegre', 'RS'),
('Maya Patel', 'Brasília', 'DF');