insert into Produtos (Descricao, Preco_Venda) values
('Nescafé - Clássico', '12.99'),
('Dolly - Guaraná', '3.50'),
('Coca-Cola - Original', '4.99'),
('Danone - Activia', '4.20'),
('Parmalat - Leite Integral', '3.89'),
('Sachet - Café', '0.50'),
('Toddy - Achocolatado', '8.90'),
('Nissin - Lámen', '2.99'),
('Arisco - Molho de Tomate', '3.25'),
('Ajinomoto - Temperos', '5.99'),
('Yoki - Arroz', '4.50'),
('Quero - Feijão', '5.20'),
('Mãe Terra - Óleo de Soja', '9.99'),
('Bombril - Esponja', '1.99'),
('BomBril - Sabão em Pó', '14.99'),
('Omo - Detergente', '12.50'),
('Downy - Amaciante', '11.90'),
('Gillette - Lâminas de Barbear', '19.99'),
('Huggies - Fraldas', '39.90'),
('Sabonete Líquido - Palmolive', '18.50'),
('Colgate - Pasta de Dente', '7.99'),
('Oral-B - Escova de Dente', '12.90'),
('Nivea - Creme', '15.99'),
('Pantene - Shampoo', '14.90'),
('Dove - Sabonete', '3.49'),
('Head & Shoulders - Shampoo Anticaspa', '16.50'),
('Mondelēz - Oreo', '5.99'),
('Nestlé - KitKat', '3.99'),
('Lacta - Bis', '2.50'),
('M&Ms - Chocolate', '6.99'),
('Snickers - Barra de Chocolate', '4.50'),
('Sucrilhos - Nescau', '11.90'),
('Kelloggs - Corn Flakes', '10.99'),
('Yoki - Milho Verde', '3.99'),
('Caramuru - Palmito', '8.50'),
('Liza - Sardinha', '4.20'),
('Real - Atum', '5.99'),
('Cerveja - Brahma', '4.99'),
('Cerveja - Skol', '4.50'),
('Cerveja - Budweiser', '5.20'),
('Vinho - Salton', '29.90'),
('Vinho - Chandon', '49.90'),
('Vinho - Garibaldi', '35.00'),
('Suco - Del Valle', '4.99'),
('Suco - Capricho', '3.99'),
('Suco - Clight', '5.50'),
('Água - Bonafont', '2.99'),
('Água - Crystal', '3.50'),
('Água - San Pellegrino', '5.99'),
('Água - Leão', '3.20');